### PR TITLE
Major overhaul and refactor

### LINKED ISSUE #3: Replace webpack with rollup
Currently, it's using `webpack` to bundle things up need to use `rollup` instead.

### PR DESCRIPTION
**Pull request by mesaugat**
* Remove babel and it's dependencies
* Use rollupjs instead of webpack
* Remove `src/KeyCode.js` and the process of transpilation, `lib/KeyCode.js` is the main library now
* Use rollup to create a `umd` build for the browser
* Update configurations and other paths to incorporate the changes
* Remove unwanted build files

Fixes #3

### CODE REVIEW

**Comment by kabirbaidhya** [comment]
@mesaugat Have you tested the changes in TypeScript with `.d.ts` file?

**Comment by mesaugat** [comment]
Pretty sure it is not right according to the changes. Need to update it.

**Comment by mesaugat** [comment]
I've updated the typescript declaration file but I've no idea if it is correct.

**Review by kabirbaidhya — APPROVED** [review]
Looks Good. I'll merge this, I'll check if we can add tests to test importing from a ts file too.

**Comment by mesaugat** [comment]
Yes do check the declaration file. Also, when you publish the package, release it as `1.0.0`

**Pull request merged**
